version: '2'

services:
  front:
    container_name: shortify-front
    build:
      context: ./front
      dockerfile: ./Dockerfile # Relative to context dir
    ports:
      - 8080:8080
    # environment:
    #   - name=value

  back:
    container_name: shortify-back
    build: 
      context: ./back
      dockerfile: ./src/main/docker/Dockerfile.graalvm-dev # Relative to context dir
      # args:
      #   - DATABASE_KIND=postgresql
      #   - DATABASE_USER=shortify
      #   - DATABASE_PASS=shortify
      #   - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/
    ports:
      - 8088:8088
    depends_on:
      - postgresql
    
  postgresql:
    container_name: shortify-postgresql
    image: postgres:15
    environment:
      - POSTGRES_USER=shortify
      - POSTGRES_PASSWORD=shortify
    volumes:
      - uri_record_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  uri_record_data: